### ISSUE TITLE
chaincode install issue 

### ISSUE THREAD

**Issue by khushalkunjir** [blockchaind/hyperledger-fabric-v2-kubernetes-dev#15]
When running this command 
./hlf.sh ccInstall 

getting below error

Error: error getting chaincode bytes: 'go list' failed with: no required module provides package github.com/blockchaind/hyperledger-fabric-v2-kubernetes-dev/key-value-chaincode: go.mod file not found in current directory or any parent directory; see 'go help modules': exit status 1

Can you please help on this?
Thank you in advance.

**Comment by blockchaind** [comment]
@khushalkunjir, a lot has changed with HLF Fabric as well as Kubernetes/containers. I'm not that involved these days but will try to find time to have a look. Do ensure your cluster has internet access as the go package is pulled from github. Let me know if that helps.

**Comment by hmoazzem** [comment]
@khushalkunjir I hope you solved this issue by now. It was because of changes in go. With an ad-hoc change we made it work. This repo is intended for showing how fabric works and how a production deployment can be approached. For a production-ready deployment we're soon open-sourcing a simple yet robust operator.
